// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR32cbW6PnCpK2gCtKn_iDVOOKEg-8QW8',
    appId: '1:920155477943:web:0e2d2f3f1e5ec24cb6fa32',
    messagingSenderId: '920155477943',
    projectId: 'fir-learn-a62aa',
    authDomain: 'fir-learn-a62aa.firebaseapp.com',
    storageBucket: 'fir-learn-a62aa.firebasestorage.app',
    measurementId: 'G-TJCZPEZCPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6k0ROula69nhZkuzHlz2kQqE3q4g2sB0',
    appId: '1:920155477943:android:81875392f361ecfdb6fa32',
    messagingSenderId: '920155477943',
    projectId: 'fir-learn-a62aa',
    storageBucket: 'fir-learn-a62aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0jPsPKG4sHT2iZtpcwREvB9fa-KOAXk',
    appId: '1:920155477943:ios:f26529086756bff4b6fa32',
    messagingSenderId: '920155477943',
    projectId: 'fir-learn-a62aa',
    storageBucket: 'fir-learn-a62aa.firebasestorage.app',
    iosBundleId: 'com.example.firebasestart',
  );
}
